-- MySQL Script generated by MySQL Workbench
-- 08/25/14 21:54:09
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES,NO_AUTO_VALUE_ON_ZERO';

-- -----------------------------------------------------
-- Schema yincart
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `yincart` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `yincart` ;

-- -----------------------------------------------------
-- Table `yincart`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yincart`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `url_key` VARCHAR(45) NOT NULL,
  `image` VARCHAR(255) NOT NULL,
  `meta_keywords` VARCHAR(255) NOT NULL,
  `meta_description` VARCHAR(255) NOT NULL,
  `sort` TINYINT NOT NULL DEFAULT 0,
  `is_navigation_menu` TINYINT NOT NULL DEFAULT 1,
  `is_inherit` TINYINT NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`category_id`),
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `yincart`.`category` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_category_category1_idx` ON `yincart`.`category` (`parent_id` ASC);


-- -----------------------------------------------------
-- Table `yincart`.`item_prop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yincart`.`item_prop` (
  `item_prop_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `type` TINYINT NOT NULL DEFAULT 1,
  `is_key` TINYINT NOT NULL DEFAULT 0,
  `is_sale` TINYINT NOT NULL DEFAULT 0,
  `is_color` TINYINT NOT NULL DEFAULT 0,
  `is_search` TINYINT NOT NULL DEFAULT 0,
  `is_must` TINYINT NOT NULL DEFAULT 0,
  `sort` TINYINT NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`item_prop_id`),
  CONSTRAINT `item_prop_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `yincart`.`category` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `item_prop_category_idx` ON `yincart`.`item_prop` (`category_id` ASC);


-- -----------------------------------------------------
-- Table `yincart`.`prop_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yincart`.`prop_value` (
  `prop_value_id` INT NOT NULL AUTO_INCREMENT,
  `item_prop_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `sort` TINYINT NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`prop_value_id`),
  CONSTRAINT `prop_value_item_prop`
    FOREIGN KEY (`item_prop_id`)
    REFERENCES `yincart`.`item_prop` (`item_prop_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `prop_value_item_prop_idx` ON `yincart`.`prop_value` (`item_prop_id` ASC);


-- -----------------------------------------------------
-- Table `yincart`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yincart`.`item` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `sku` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` TEXT NOT NULL,
  `short_description` TEXT NOT NULL,
  `meta_keywords` VARCHAR(255) NOT NULL,
  `meta_description` VARCHAR(255) NOT NULL,
  `url_key` VARCHAR(45) NOT NULL,
  `news_from_date` INT NOT NULL DEFAULT 0,
  `news_to_date` INT NOT NULL DEFAULT 0,
  `original_price` FLOAT NOT NULL DEFAULT 0,
  `price` FLOAT NOT NULL DEFAULT 0,
  `weight` FLOAT NOT NULL DEFAULT 0,
  `shipping_fee` FLOAT NOT NULL DEFAULT 0,
  `is_free_shipping` TINYINT NOT NULL DEFAULT 0,
  `stock_qty` INT NOT NULL DEFAULT 0,
  `notify_stock_qty` INT NOT NULL DEFAULT 0,
  `min_sale_qty` INT NOT NULL DEFAULT 1,
  `max_sale_qty` INT NOT NULL DEFAULT 0,
  `qty_increments` INT NOT NULL DEFAULT 1,
  `clicks` INT NOT NULL DEFAULT 0,
  `wishes` INT NOT NULL DEFAULT 0,
  `sales` INT NOT NULL DEFAULT 0,
  `sort` SMALLINT NOT NULL DEFAULT 0,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`item_id`),
  CONSTRAINT `item_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `yincart`.`category` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `item_category_idx` ON `yincart`.`item` (`category_id` ASC);

CREATE INDEX `INDEX` ON `yincart`.`item` (`sku` ASC, `url_key` ASC);


-- -----------------------------------------------------
-- Table `yincart`.`item_img`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yincart`.`item_img` (
  `item_img_id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `sort` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`item_img_id`),
  CONSTRAINT `item_img_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `yincart`.`item` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `item_img_item_idx` ON `yincart`.`item_img` (`item_id` ASC);


-- -----------------------------------------------------
-- Table `yincart`.`sku`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yincart`.`sku` (
  `sku_id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  `sku` VARCHAR(45) NOT NULL,
  `properties` VARCHAR(255) NOT NULL,
  `propertyNames` VARCHAR(255) NOT NULL,
  `stock_qty` INT NOT NULL DEFAULT 0,
  `price` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`sku_id`),
  CONSTRAINT `sku_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `yincart`.`item` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `sku_item_idx` ON `yincart`.`sku` (`item_id` ASC);


-- -----------------------------------------------------
-- Table `yincart`.`item_prop_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yincart`.`item_prop_value` (
  `item_prop_value_id` INT NOT NULL AUTO_INCREMENT,
  `item_id` INT NOT NULL,
  `item_prop_id` INT NOT NULL,
  `prop_value_id` INT NOT NULL,
  `custom_prop_value` VARCHAR(45) NOT NULL,
  `image_url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`item_prop_value_id`),
  CONSTRAINT `ipv_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `yincart`.`item` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ipv_item_prop`
    FOREIGN KEY (`item_prop_id`)
    REFERENCES `yincart`.`item_prop` (`item_prop_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ipv_prop_value`
    FOREIGN KEY (`prop_value_id`)
    REFERENCES `yincart`.`prop_value` (`prop_value_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `ipv_item_idx` ON `yincart`.`item_prop_value` (`item_id` ASC);

CREATE INDEX `ipv_item_prop_idx` ON `yincart`.`item_prop_value` (`item_prop_id` ASC);

CREATE INDEX `ipv_prop_value_idx` ON `yincart`.`item_prop_value` (`prop_value_id` ASC);


-- -----------------------------------------------------
-- Table `yincart`.`customer_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yincart`.`customer_group` (
  `customer_group_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`customer_group_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `yincart`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yincart`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `customer_group_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `register_time` INT NOT NULL,
  `last_login_time` INT NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`customer_id`),
  CONSTRAINT `fk_customer_customer_group1`
    FOREIGN KEY (`customer_group_id`)
    REFERENCES `yincart`.`customer_group` (`customer_group_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_customer_customer_group1_idx` ON `yincart`.`customer` (`customer_group_id` ASC);


-- -----------------------------------------------------
-- Table `yincart`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yincart`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `total_price` FLOAT NOT NULL DEFAULT 0,
  `promotions` VARCHAR(45) NOT NULL,
  `created_time` INT NOT NULL DEFAULT 0,
  `payment_time` INT NOT NULL DEFAULT 0,
  `shipping_time` INT NOT NULL DEFAULT 0,
  `completed_time` INT NOT NULL DEFAULT 0,
  `canceled_time` INT NOT NULL DEFAULT 0,
  `payment_type` TINYINT NOT NULL DEFAULT 0,
  `payment_transaction_no` VARCHAR(45) NOT NULL,
  `shipping_type` TINYINT NOT NULL DEFAULT 0,
  `shipping_address` VARCHAR(255) NOT NULL,
  `is_free_shipping` TINYINT NOT NULL DEFAULT 0,
  `shipping_fee` FLOAT NOT NULL DEFAULT 0,
  `remark` VARCHAR(255) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`order_id`),
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `yincart`.`customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_order_customer1_idx` ON `yincart`.`order` (`customer_id` ASC);


-- -----------------------------------------------------
-- Table `yincart`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yincart`.`order_item` (
  `order_item_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `sku_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `image_url` VARCHAR(255) NOT NULL,
  `propertyNames` VARCHAR(255) NOT NULL,
  `original_price` FLOAT NOT NULL DEFAULT 0,
  `promotions` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL DEFAULT 0,
  `qty` INT NOT NULL DEFAULT 1,
  `total_price` FLOAT NOT NULL DEFAULT 0,
  PRIMARY KEY (`order_item_id`),
  CONSTRAINT `order_item_order`
    FOREIGN KEY (`order_id`)
    REFERENCES `yincart`.`order` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `order_item_item`
    FOREIGN KEY (`item_id`)
    REFERENCES `yincart`.`item` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_item_sku1`
    FOREIGN KEY (`sku_id`)
    REFERENCES `yincart`.`sku` (`sku_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `order_item_order_idx` ON `yincart`.`order_item` (`order_id` ASC);

CREATE INDEX `order_item_item_idx` ON `yincart`.`order_item` (`item_id` ASC);

CREATE INDEX `fk_order_item_sku1_idx` ON `yincart`.`order_item` (`sku_id` ASC);


-- -----------------------------------------------------
-- Table `yincart`.`address_area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yincart`.`address_area` (
  `address_area_id` INT NOT NULL AUTO_INCREMENT,
  `parent_id` INT NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  `grade` TINYINT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `language` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`address_area_id`),
  CONSTRAINT `fk_address_area_address_area1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `yincart`.`address_area` (`address_area_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_address_area_address_area1_idx` ON `yincart`.`address_area` (`parent_id` ASC);


-- -----------------------------------------------------
-- Table `yincart`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yincart`.`address` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `area` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `zip_code` VARCHAR(10) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `mobile` VARCHAR(15) NOT NULL,
  `contact_name` VARCHAR(45) NOT NULL,
  `is_default` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`address_id`),
  CONSTRAINT `fk_address_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `yincart`.`customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_address_customer1_idx` ON `yincart`.`address` (`customer_id` ASC);


-- -----------------------------------------------------
-- Table `yincart`.`wish`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yincart`.`wish` (
  `wish_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  PRIMARY KEY (`wish_id`),
  CONSTRAINT `fk_wish_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `yincart`.`customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_wish_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `yincart`.`item` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_wish_customer1_idx` ON `yincart`.`wish` (`customer_id` ASC);

CREATE INDEX `fk_wish_item1_idx` ON `yincart`.`wish` (`item_id` ASC);


-- -----------------------------------------------------
-- Table `yincart`.`shippint_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yincart`.`shippint_cart` (
  `shippint_cart_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `sku_id` INT NOT NULL,
  `qty` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`shippint_cart_id`),
  CONSTRAINT `fk_shippint_cart_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `yincart`.`customer` (`customer_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_shippint_cart_item1`
    FOREIGN KEY (`item_id`)
    REFERENCES `yincart`.`item` (`item_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_shippint_cart_sku1`
    FOREIGN KEY (`sku_id`)
    REFERENCES `yincart`.`sku` (`sku_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_shippint_cart_customer1_idx` ON `yincart`.`shippint_cart` (`customer_id` ASC);

CREATE INDEX `fk_shippint_cart_item1_idx` ON `yincart`.`shippint_cart` (`item_id` ASC);

CREATE INDEX `fk_shippint_cart_sku1_idx` ON `yincart`.`shippint_cart` (`sku_id` ASC);


-- -----------------------------------------------------
-- Table `yincart`.`promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `yincart`.`promotion` (
  `promotion_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`promotion_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Data for table `yincart`.`category`
-- -----------------------------------------------------
START TRANSACTION;
USE `yincart`;
INSERT INTO `yincart`.`category` (`category_id`, `parent_id`, `name`, `url_key`, `image`, `meta_keywords`, `meta_description`, `sort`, `is_navigation_menu`, `is_inherit`, `status`) VALUES (0, 0, '0', '0', '0', '0', '0', 0, 0, 0, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `yincart`.`item_prop`
-- -----------------------------------------------------
START TRANSACTION;
USE `yincart`;
INSERT INTO `yincart`.`item_prop` (`item_prop_id`, `category_id`, `name`, `type`, `is_key`, `is_sale`, `is_color`, `is_search`, `is_must`, `sort`, `status`) VALUES (0, 0, '0', 0, 0, 0, 0, 0, 0, 0, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `yincart`.`prop_value`
-- -----------------------------------------------------
START TRANSACTION;
USE `yincart`;
INSERT INTO `yincart`.`prop_value` (`prop_value_id`, `item_prop_id`, `name`, `sort`, `status`) VALUES (0, 0, '0', 0, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `yincart`.`item`
-- -----------------------------------------------------
START TRANSACTION;
USE `yincart`;
INSERT INTO `yincart`.`item` (`item_id`, `category_id`, `sku`, `name`, `description`, `short_description`, `meta_keywords`, `meta_description`, `url_key`, `news_from_date`, `news_to_date`, `original_price`, `price`, `weight`, `shipping_fee`, `is_free_shipping`, `stock_qty`, `notify_stock_qty`, `min_sale_qty`, `max_sale_qty`, `qty_increments`, `clicks`, `wishes`, `sales`, `sort`, `status`) VALUES (0, 0, '0', '0', '0', '0', '0', '0', '0', 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `yincart`.`sku`
-- -----------------------------------------------------
START TRANSACTION;
USE `yincart`;
INSERT INTO `yincart`.`sku` (`sku_id`, `item_id`, `sku`, `properties`, `propertyNames`, `stock_qty`, `price`) VALUES (0, 0, '0', '0', '0', 0, 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `yincart`.`address_area`
-- -----------------------------------------------------
START TRANSACTION;
USE `yincart`;
INSERT INTO `yincart`.`address_area` (`address_area_id`, `parent_id`, `path`, `grade`, `name`, `language`) VALUES (0, 0, '0', 0, '0', '0');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;